# Generated by Django 5.1.6 on 2025-04-10 22:05

import django.db.models.deletion
import summarizer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=summarizer.models.PromptRequest.user_directory_path)),
                ('internal', models.BooleanField(default=False)),
                ('external', models.BooleanField(default=False)),
                ('processed_internally', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('processed_externally', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prompt_request',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prompt_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizer.promptrequest')),
            ],
            options={
                'db_table': 'prompt_response',
                'ordering': ['-created'],
            },
        ),
    ]
