# Generated by Django 5.1.6 on 2025-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptrequest',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
