# Generated by Django 5.1.6 on 2025-04-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0002_promptrequest_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptrequest',
            name='external',
        ),
        migrations.RemoveField(
            model_name='promptrequest',
            name='internal',
        ),
        migrations.AddField(
            model_name='promptresponse',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promptresponse',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
