# Generated by Django 5.1.6 on 2025-04-10 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0004_promptrequest_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptinternalrequest',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='promptinternalrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='promptinternalrequest',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='promptinternalrequest',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='promptinternalrequest',
            name='title',
        ),
        migrations.RemoveField(
            model_name='promptinternalrequest',
            name='to',
        ),
        migrations.AddField(
            model_name='promptinternalrequest',
            name='accepted_internally',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='promptinternalrequest',
            table='prompt_internal_request',
        ),
        migrations.AlterModelTable(
            name='promptinternalresponse',
            table='prompt_internal_response',
        ),
        migrations.CreateModel(
            name='PromptExternalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('accepted_internally', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizer.promptcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prompt_external_request',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromptExternalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prompt_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizer.promptexternalrequest')),
            ],
            options={
                'db_table': 'prompt_external_response',
                'ordering': ['-created'],
            },
        ),
    ]
