# Generated by Django 5.1.6 on 2025-02-05 22:00

import django.db.models.deletion
import template_agent.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_reference', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt_category',
            },
        ),
        migrations.CreateModel(
            name='PromptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('file', models.FileField(upload_to=template_agent.models.PromptRequest.user_directory_path)),
                ('processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_agent.promptcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prompt_request',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prompt_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_agent.promptrequest')),
            ],
            options={
                'db_table': 'prompt_response',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
                ('file', models.FileField(upload_to=template_agent.models.Template.user_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prompt_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_agent.promptrequest')),
            ],
            options={
                'db_table': 'template',
                'ordering': ['-created'],
            },
        ),
    ]
