# Generated by Django 5.1.6 on 2025-02-09 18:56

import template_agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_agent', '0002_rename_user_promptrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptrequest',
            name='cc',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promptrequest',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptrequest',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promptrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promptrequest',
            name='to',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promptrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=template_agent.models.PromptRequest.user_directory_path),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=template_agent.models.Template.user_directory_path),
        ),
    ]
